#!/bin/bash
# tdp daemon
# chkconfig: 345 20 80
# description: tdp tomcat control script
# processname: tomcat
TDP_PATH="/datalex/tomcat/bin/tdp_ctl.sh"
TDP=tdp_ctl.sh
TDPOPTS=" tomcat"
USER=jbinst
NAME=TDP_CONTROL_TOMCAT
DESC="simple tdp startup script"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
	start)
    printf "%-50s" "Starting $NAME..."
   echo "Removing SESSIONS.ser..."
   rm -f /opt/datalex/tomcat/work/Catalina/localhost/jetBlue/SESSIONS.ser
   su - $USER -c "$TDP_PATH start $TDPOPTS"
   PID=`ps -ef |grep java | grep $USER|grep datalex | awk '{print $2}'`
   #PID=` su - $USER -c "$TDP_PATH start $TDPOPTS" `
    echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE >/dev/null 2>&1 `
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "TDP Running at $PID"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME "
            PID=`cat $PIDFILE > /dev/null 2>&1`
        if [ -f $PIDFILE ]; then
        su - $USER -c "$TDP_PATH stop $TDPOPTS"    
	#kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;
 
restart)
    $0 stop
$0 sleep 10
    $0 start
;;
	 
	*)
	        echo "Usage: $0 {status|start|stop|restart}"
	        exit 1
	esac
