---
- name: Provisioning Playbook
  hosts: localhost 
  become: true
  roles:
    - dcr_server-setup

  tasks:
    - name: Add ansible user to sudoers
      copy:
        content: 'ani ALL=(ALL)	NOPASSWD:	ALL'
        dest: /etc/sudoers.d/ani
        owner: root 
        group: root 
        mode: '0440'
        validate: /usr/sbin/visudo -csf %s
