---
- name: Provisioning Playbook
  hosts: all
  become: true
  roles:
    - jboss_server

  tasks:
    - name: Add ansible user to sudoers
      copy:
        content: 'ani ALL=(ALL)	NOPASSWD:	ALL'
        dest: /etc/sudoers.d/ani
        owner: root
        group: root
        mode: '0440'
        #validate: /usr/sbin/visudo -csf %s
